---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIULy2a7fqqSrj3R1DUBgfIW4uocdQwDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkxMTIwMTc1OTAwWhcNMjQxMTE4MTc1OTAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    AKjZ/Jrg6vAC0DmaQ37Sx3J8FIphviPIYQCf31S1KYwC3YHSNxJxw4MRLuQGIugQ
    DWP4CKbJSCjnQUrA7zlP/rvvriqavhh3ofeNmJMBECwyYihF6KyZUPULVivCS/iT
    pBC1+VmzTjvuwHPliPK5rWObf5mwg7IP0EPMjV7DyDv4badiLbP5QPjgwqic5DFu
    RxIFvEArQN1fXwhUg0VehgiXKCkH1Zvx9U21Np80+51etnUpVcOsWzMxyCzi+niB
    U6rp/BhaNsl2I6ib5JUqa6ptjdlTMQq7Zc3yZQOm6qq+SlRAH4YifOoVpNUnXeV9
    55CU82D1mF/WITbv6HIzNQNJZzXIeO1y+bu7NMkKtATx6vkwtN/zVH6utWNlvHnW
    7j9NHpowyBsOKXwhnBq/4HfAPjALYMwjhDaYMAKvbLNqsbWeRc2CYZEsLKMjJSMr
    NNWDJJ/7rf0aCufcTtBu6mdj6Ggu4UjLA1jGpXpc8PIIYCp/YE9d1IfYSWO8QQig
    m0Mk9QCBNMILovGIwZ5BvgDIW4qNjJA2OU6BcSMZ3JtKVIy2otF8p03HP2OQB7Fj
    4MC5itW8dZg+JsAOHY92e1KIQETGv4xm9Qkz45tsDQ3ltg+80sUklMxry1YohETF
    FXoXVIbXabV9F5o+FU7mM/QnzS+d59JM0NHg1vVOVv11AgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSePM32V4jZW5sj
    TEi7y/BEvnKrrTANBgkqhkiG9w0BAQ0FAAOCAgEAWMQ/hrOKMmzfXc5phJiz1Evt
    GMhLD332ra4alyrI9VxWVIlV5D5t9FWFJbXG6x3ggw0r5GEfszFlGtc1oWMRlNev
    PbX0BQaT3ZfeGWJEhG9Q/d5xg8QPqD1RG6gnVIT7IcmwuboLbP4Kqo7kxqJfzKS7
    yWL+k0AsAKF00dotXi+5mLotw+Qk0E2yvinyOOG3IpLUzIBUOf2Hu6UMT91JsvJI
    825aMsJ+Ij/lS6nNIIFeXyr5+upxBXCepW6oTCPT3vShkobq01MamZ8LFBUTrE3v
    7OGNAii4Zzofj/Zw3j4e73IJ0OxlQadjL+17Gs7xj5SCnVyn8vBke2OOj42et+rI
    AbIHdzmCTGraVDzuN5SIIZvQWSsv2UfXCPqEs1sV0MKxP0Hs7VnEXJfLTc02kc5P
    qlPdGjEFb/dOrP4/rCUIPw9n73Os9iFlrCsaTpzKgyj5kPlVDtkCH1/fb2fCdI02
    00GtqY0m7WExNyBVUBM8RqzOdyJkSoCaSzPg7hQyYV64yVgW8N/54Xqe9eXajSTq
    Au5nhfbuUtyvw28T1goCD8fwQw4jvqkhRo1PqIrABIU9b3Z3cRvX9SFNVEpMva0A
    5IBt++aPeiqK0/CShQWd7yTF0YUNJTnLnWBlRcjhoRwwsZ3TDEFDLaRmh2b1bwJx
    9MJuLrkI1iST9yPf/Qo=
    -----END CERTIFICATE-----
    
